import React, { useEffect, useState } from 'react';
import { CATEGORIES, COLLECTIBLES, DEMO_POSTS, HOBBIES, dailyRecommendation, hobbyById, itemById, ya, type Collectible, type Hobby, type HobbyId, type ImageSource } from './data.js';
import { INITIAL_STATE, normalizeState, previewBuy, previewSell, toggleBookmark, toggleFollow, toggleInterest, toggleLike, type AppState } from './state.js';
import './app.css';

const STORE_KEY = 'game113-app-demo-v1';
const NAV = [
  { id: 'home', label: '首页', icon: 'home' }, { id: 'discover', label: '发现', icon: 'search' },
  { id: 'market', label: '市集', icon: 'market' }, { id: 'warehouse', label: '仓库', icon: 'box' },
  { id: 'community', label: '同好', icon: 'people' },
] as const;

type IconName = 'home' | 'search' | 'market' | 'box' | 'people' | 'arrow' | 'back' | 'heart' | 'coin' | 'user' | 'book' | 'settings' | 'plus' | 'close' | 'check' | 'spark' | 'camera';
function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, React.ReactNode> = {
    home: <><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/><path d="M9 21v-7h6v7"/></>,
    search: <><circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/></>,
    market: <><path d="M4 8h16l-1 13H5L4 8Z"/><path d="M8 9V6a4 4 0 0 1 8 0v3"/></>,
    box: <><path d="M3 8 12 3l9 5v11l-9 5-9-5z"/><path d="m3 8 9 5 9-5M12 13v11"/></>,
    people: <><circle cx="8" cy="8" r="3"/><path d="M2 21v-2a6 6 0 0 1 12 0v2M16 5a3 3 0 0 1 0 6m1 4a5 5 0 0 1 5 5v1"/></>,
    arrow: <><path d="M4 12h16m-6-6 6 6-6 6"/></>,
    back: <><path d="M20 12H4m6-6-6 6 6 6"/></>,
    heart: <path d="M20.5 5.5a5.5 5.5 0 0 0-7.8 0L12 6.2l-.7-.7a5.5 5.5 0 0 0-7.8 7.8L12 22l8.5-8.7a5.5 5.5 0 0 0 0-7.8Z"/>,
    coin: <><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><path d="M9 12h6m-3-3v6"/></>,
    user: <><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,
    book: <><path d="M12 5c-3-2-6-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1ZM12 5v15"/></>,
    settings: <><circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M19 5l-2 2M7 17l-2 2"/></>,
    plus: <path d="M12 4v16M4 12h16"/>, close: <path d="M5 5 19 19M19 5 5 19"/>, check: <path d="m4 12 5 5L20 6"/>,
    spark: <><path d="m12 2 1.5 7L21 12l-7.5 3L12 22l-1.5-7L3 12l7.5-3L12 2Z"/></>,
    camera: <><path d="M3 7h4l2-3h6l2 3h4v13H3z"/><circle cx="12" cy="13" r="4"/></>,
  };
  return <svg className="g113-icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

function Image({ source, alt, className = '' }: { source: ImageSource; alt: string; className?: string }) {
  return <div className={`g113-image ${className}`}><img src={source.src} alt={alt}/>{source.kind === 'ai-demo' && <span className="g113-image-tag">AI 示意图</span>}</div>;
}
function Eyebrow({ children }: { children: React.ReactNode }) { return <div className="g113-eyebrow">{children}</div>; }
function Action({ children, onClick, ghost = false, disabled = false, icon }: { children: React.ReactNode; onClick: () => void; ghost?: boolean; disabled?: boolean; icon?: IconName }) {
  return <button className={`g113-action ${ghost ? 'g113-action--ghost' : ''}`} onClick={onClick} disabled={disabled}>{children}{icon && <Icon name={icon} size={18}/>}</button>;
}
function SectionHead({ title, note, action, onAction }: { title: string; note?: string; action?: string; onAction?: () => void }) {
  return <div className="g113-section-head"><div><h2>{title}</h2>{note && <p>{note}</p>}</div>{action && onAction && <button className="g113-text-button" onClick={onAction}>{action} <Icon name="arrow" size={16}/></button>}</div>;
}

const readHash = () => decodeURI(window.location.hash.replace(/^#\/?/, '')) || 'home';
function useRoute() {
  const [route, setRoute] = useState(readHash);
  useEffect(() => { const changed = () => setRoute(readHash()); window.addEventListener('hashchange', changed); return () => window.removeEventListener('hashchange', changed); }, []);
  const go = (next: string) => { window.location.hash = `/${next}`; setRoute(next); window.scrollTo({ top: 0, behavior: 'auto' }); };
  return { route, go };
}
function loadState(): AppState {
  try { return normalizeState(JSON.parse(window.localStorage.getItem(STORE_KEY) || 'null')); } catch { return INITIAL_STATE; }
}

export function App({ onExit }: { onExit?: () => void }) {
  const { route, go } = useRoute();
  useEffect(() => { const previous = document.title; document.title = '雅趣：第二人生'; return () => { document.title = previous; }; }, []);
  const [state, setState] = useState<AppState>(loadState);
  const [notice, setNotice] = useState('');
  const [dialog, setDialog] = useState<{ title: string; body: string; action: string; run: () => void } | null>(null);
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('all');
  const [marketFilter, setMarketFilter] = useState('all');
  const [hobbyTab, setHobbyTab] = useState('overview');
  const [trendPeriod, setTrendPeriod] = useState('30天');
  const [selectedSpot, setSelectedSpot] = useState<number | null>(null);
  const [examAnswer, setExamAnswer] = useState<number | null>(null);
  const [draft, setDraft] = useState({ title: '', text: '', hobbyId: 'watch' as HobbyId });
  const [uploadName, setUploadName] = useState('');
  useEffect(() => { try { window.localStorage.setItem(STORE_KEY, JSON.stringify(state)); } catch { /* private mode: keep in memory */ } }, [state]);
  useEffect(() => { if (!notice) return; const id = window.setTimeout(() => setNotice(''), 4200); return () => window.clearTimeout(id); }, [notice]);
  const update = (fn: (s: AppState) => AppState) => setState((s) => fn(s));
  const notify = (message: string) => setNotice(message);
  const segments = route.split('/');
  const page = segments[0];
  const subId = segments[1];
  const active = NAV.some((n) => n.id === page) ? page : page === 'hobby' ? 'discover' : page === 'item' ? 'market' : page === 'inspect' || page === 'care' || page === 'play' ? 'warehouse' : page === 'post' || page === 'compose' || page === 'circle' ? 'community' : '';
  const openItem = (id: string) => go(`item/${id}`);
  const openHobby = (id: string) => { setHobbyTab('overview'); go(`hobby/${id}`); };
  const chosenRecommendation = dailyRecommendation(state.interests, new Date());
  const pending = state.owned.filter((id) => !state.inspected.includes(id));
  const ownedItems = state.owned.map((id) => itemById(id)).filter((x): x is Collectible => Boolean(x));

  const buy = (item: Collectible) => setDialog({ title: '确认演示买入', body: `这笔操作只更新本机 Demo：${item.name}，花费 ◎ ${ya(item.price)}。不会发起真实交易。`, action: '确认买入', run: () => { const result = previewBuy(state, item.id); if (result.error) notify(result.error); else { setState(result.state); notify('已放入待鉴区 · 本机演示'); go('warehouse'); } setDialog(null); } });
  const sell = (item: Collectible) => setDialog({ title: '确认演示卖出', body: `${item.name} 将从本机仓库移除，按演示价扣除 5% 手续费。此处不是实际交易。`, action: '确认卖出', run: () => { const result = previewSell(state, item.id); if (result.error) notify(result.error); else { setState(result.state); notify('已完成本机演示卖出'); go('warehouse'); } setDialog(null); } });

  function HobbyCard({ hobby, compact = false }: { hobby: Hobby; compact?: boolean }) {
    return <button className={`g113-hobby-card ${compact ? 'g113-hobby-card--compact' : ''}`} onClick={() => openHobby(hobby.id)}><Image source={hobby.image} alt={`${hobby.name}示意图`}/><div className="g113-hobby-copy"><small>{hobby.categoryLabel}</small><h3>{hobby.name}</h3><p>{hobby.tagline}</p><span>进入爱好馆 <Icon name="arrow" size={15}/></span></div></button>;
  }
  function ItemCard({ item }: { item: Collectible }) {
    return <button className="g113-item-card" onClick={() => openItem(item.id)}><Image source={item.image} alt={`${item.name}示意图`}/><div className="g113-item-copy"><small>{hobbyById(item.hobbyId)?.name} · {item.tier}</small><h3>{item.name}</h3><p>{item.subtitle}</p><div className="g113-item-price"><span>◎ {ya(item.price)}</span><em className={item.change < 0 ? 'down' : ''}>{item.change > 0 ? '+' : ''}{item.change.toFixed(1)}%</em></div></div></button>;
  }
  function Subhead({ title, kicker, back = 'home' }: { title: string; kicker?: string; back?: string }) {
    return <div className="g113-subhead"><button className="g113-back" onClick={() => go(back)} aria-label="返回"><Icon name="back"/></button><div>{kicker && <Eyebrow>{kicker}</Eyebrow>}<h1>{title}</h1></div></div>;
  }

  const main = (() => {
    if (page === 'welcome' || (!state.onboarded && page === 'home')) return <div className="g113-welcome"><div className="g113-welcome-hero"><Image source={HOBBIES[0].image} alt="机械表氛围示意图"/><div className="g113-welcome-copy"><Eyebrow>人生下半场 · 新爱好正当时</Eyebrow><h1>雅趣<span>·</span>第二人生</h1><p>去认识一件有趣的事，遇见愿意一起聊的人。</p><Action onClick={() => go('onboarding')} icon="arrow">开启第二兴趣</Action></div></div><div className="g113-welcome-foot"><span>发现兴趣</span><span>收藏成长</span><span>同好交流</span></div></div>;
    if (page === 'onboarding') return <div className="g113-page g113-onboarding"><Subhead title="先从喜欢的开始" kicker="WELCOME / 第一步" back="welcome"/><p className="g113-lead">选几门你愿意了解的爱好。以后每天，我们也会带你认识一个新的世界。</p><div className="g113-choice-grid">{HOBBIES.map((h) => <button key={h.id} className={`g113-choice ${state.interests.includes(h.id) ? 'selected' : ''}`} onClick={() => update((s) => toggleInterest(s, h.id))}><Image source={h.image} alt={`${h.name}示意图`}/><span>{h.name}</span>{state.interests.includes(h.id) && <i><Icon name="check" size={16}/></i>}</button>)}</div><div className="g113-onboarding-actions"><span>已选 {state.interests.length} 门 · 随时可以更改</span><Action onClick={() => { update((s) => ({ ...s, onboarded: true })); go('home'); }} icon="arrow">进入雅趣</Action></div></div>;
    if (page === 'home') return <div className="g113-page g113-home"><div className="g113-home-top"><div><Eyebrow>WELCOME BACK / 今天也慢慢来</Eyebrow><h1>愿你今天，<br/>又遇见一点新趣味。</h1></div><div className="g113-date-note">今日推荐，<br/>从你尚未认识的爱好开始。</div></div><div className="g113-home-grid"><div className="g113-hero-card"><Image source={chosenRecommendation.image} alt={`${chosenRecommendation.name}推荐示意图`}/><div className="g113-hero-copy"><Eyebrow>今日推荐 · 一门新爱好</Eyebrow><h2>认识一个新爱好：<br/>{chosenRecommendation.name}</h2><p>{chosenRecommendation.tagline}</p><Action onClick={() => openHobby(chosenRecommendation.id)} icon="arrow">先看看</Action></div></div><div className="g113-fresh-card"><Eyebrow>DAILY NOTES</Eyebrow><h2>今日新鲜</h2><button onClick={() => openItem('wine-01')}><span className="g113-fresh-thumb"><img src={HOBBIES[1].image.src} alt="红酒示意图"/></span><span><b>红酒馆新开一件</b><small>认识产区，也认识杯中的故事。</small></span><Icon name="arrow" size={17}/></button><button onClick={() => go('community')}><span className="g113-fresh-thumb"><img src={HOBBIES[3].image.src} alt="木工示意图"/></span><span><b>同好分享 · 木工小椅</b><small>一把小椅子的诞生过程。</small></span><Icon name="arrow" size={17}/></button><button onClick={() => go('market')}><span className="g113-fresh-thumb"><img src={HOBBIES[2].image.src} alt="核桃示意图"/></span><span><b>看看今天的市集</b><small>游戏内行情，温和日更。</small></span><Icon name="arrow" size={17}/></button></div></div><section><SectionHead title="为你打开的兴趣" note="生活不止一种精彩，总有一个兴趣适合现在的你。" action="查看全部" onAction={() => go('discover')}/><div className="g113-hobby-row">{HOBBIES.map((h) => <HobbyCard key={h.id} hobby={h} compact/>)}</div></section><div className="g113-home-lower"><section><SectionHead title="继续培养" note="从上一件藏品，继续向前走。" action="我的仓库" onAction={() => go('warehouse')}/><button className="g113-continue" onClick={() => go(pending.length ? `inspect/${pending[0]}` : 'warehouse')}><img src={(pending.length ? itemById(pending[0]) : ownedItems[0])?.image.src || HOBBIES[0].image.src} alt="继续培养示意图"/><span><small>{pending.length ? '待鉴区 · 下一步' : '仓库 · 下一步'}</small><b>{pending.length ? '细看一件新藏品' : '看看自己的收藏'}</b><em>每一件，都值得慢慢认识。</em></span><Icon name="arrow"/></button></section><section><SectionHead title="同好正在聊" note="分享见闻，让兴趣有了回声。" action="进入同好" onAction={() => go('community')}/><div className="g113-home-posts">{DEMO_POSTS.slice(0, 2).map((p) => <button key={p.id} onClick={() => go(`post/${p.id}`)}><span className="g113-avatar">{p.initials}</span><span><b>{p.title}</b><small>{p.author} · {p.time}</small></span><Icon name="arrow" size={17}/></button>)}</div></section></div></div>;
    if (page === 'discover') { const list = HOBBIES.filter((h) => (category === 'all' || h.category === category) && `${h.name}${h.tagline}${h.english}`.toLowerCase().includes(query.toLowerCase())); return <div className="g113-page"><div className="g113-page-intro"><Eyebrow>DISCOVER / 发现</Eyebrow><h1>新的热爱，从这里开始。</h1><p>不必精通，先跟着好奇心走一小段。</p></div><div className="g113-toolbar"><label className="g113-search"><Icon name="search"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索你想了解的爱好" aria-label="搜索爱好"/></label><span>已开 {HOBBIES.length} 座爱好馆</span></div><div className="g113-chip-row">{CATEGORIES.map((c) => <button key={c.id} className={category === c.id ? 'active' : ''} onClick={() => setCategory(c.id)}>{c.name}</button>)}</div><div className="g113-hobby-grid">{list.map((h) => <HobbyCard key={h.id} hobby={h}/>)}</div>{!list.length && <div className="g113-empty"><h2>这一类正在筹备中</h2><p>我们会先让每座爱好馆有扎实的照片与知识，再邀请你来逛。</p><Action onClick={() => setCategory('all')} ghost>看看已开馆的爱好</Action></div>}</div>; }
    if (page === 'hobby') { const h = hobbyById(subId); if (!h) return <div className="g113-page"><Subhead title="未找到爱好馆" back="discover"/></div>; const items = COLLECTIBLES.filter((x) => x.hobbyId === h.id); return <div className="g113-page"><Subhead title={h.name} kicker={`${h.english.toUpperCase()} / 爱好馆`} back="discover"/><div className="g113-hobby-hero"><Image source={h.image} alt={`${h.name}爱好馆示意图`}/><div><Eyebrow>{h.categoryLabel} · {h.people}</Eyebrow><h2>{h.tagline}</h2><p>{h.intro}</p><button className="g113-inline-link" onClick={() => update((s) => toggleFollow(s, h.id))}>{state.following.includes(h.id) ? '✓ 已关注这门爱好' : '+ 关注这门爱好'}</button></div></div><div className="g113-tabs">{[['overview', '总览'], ['collection', '馆藏'], ['learn', '学习'], ['friends', '同好']].map(([id, label]) => <button key={id} className={hobbyTab === id ? 'active' : ''} onClick={() => setHobbyTab(id)}>{label}</button>)}</div>{hobbyTab === 'overview' && <div className="g113-two-col"><div className="g113-paper"><Eyebrow>START HERE</Eyebrow><h2>从这三件事，慢慢入门</h2><ol>{h.learning.map((x) => <li key={x}>{x}</li>)}</ol><Action onClick={() => setHobbyTab('learn')} icon="arrow">开始认识</Action></div><div className="g113-paper"><Eyebrow>COLLECTION</Eyebrow><h2>馆藏的一角</h2><p>每一件藏品，都有值得细看的地方。</p><div className="g113-mini-item" onClick={() => openItem(items[0].id)} role="button" tabIndex={0} onKeyDown={(e) => e.key === 'Enter' && openItem(items[0].id)}><img src={items[0].image.src} alt="藏品示意图"/><span>{items[0].name}<small>查看藏品档案 →</small></span></div></div></div>}{hobbyTab === 'collection' && <div className="g113-item-grid">{items.map((x) => <ItemCard key={x.id} item={x}/>)}</div>}{hobbyTab === 'learn' && <div className="g113-paper g113-reading"><Eyebrow>知识入门</Eyebrow><h2>{h.name}，先从看懂开始</h2><p>{h.intro}</p>{h.learning.map((x, i) => <button key={x} className="g113-learn-row" onClick={() => go(`inspect/${items[0].id}`)}><span>0{i + 1}</span><b>{x}</b><Icon name="arrow" size={18}/></button>)}<p className="g113-demo-note">细看互动规则尚未接入；这里展示应用流程与知识卡样式。</p></div>}{hobbyTab === 'friends' && <div className="g113-paper"><Eyebrow>PEOPLE</Eyebrow><h2>和同好聊聊</h2><p>{h.people}，也许下一位朋友就在这里。</p><Action onClick={() => go('community')} icon="arrow">进入同好圈</Action></div>}</div>; }
    if (page === 'market') { const items = COLLECTIBLES.filter((x) => marketFilter === 'all' || x.hobbyId === marketFilter); return <div className="g113-page"><div className="g113-page-intro"><Eyebrow>THE MARKET / 市集</Eyebrow><h1>遇见值得细看的藏品。</h1><p>用雅钱探索虚拟收藏，在知识与品味中慢慢成长。</p></div><div className="g113-market-top"><div className="g113-market-note"><Eyebrow>游戏内行情 · 今日板块</Eyebrow><h2>把行情当作一页收藏日记。</h2><p>每日更新一次，波动被有意放慢。这里没有收益承诺，也没有催促买入的倒计时。</p><div className="g113-trend-legend"><span><i/> 文玩核桃 <b>+0.6%</b></span><span><i/> 机械表 <b>+0.4%</b></span><span><i/> 红酒 <b className="down">−0.2%</b></span></div></div><div className="g113-trend"><div className="g113-trend-header"><span>板块走势 · 演示数据</span><div>{['30天', '90天', '1年'].map((x) => <button key={x} className={trendPeriod === x ? 'active' : ''} onClick={() => setTrendPeriod(x)}>{x}</button>)}</div></div><svg viewBox="0 0 440 150" role="img" aria-label="演示行情折线图"><path d="M0 117H440M0 77H440M0 37H440" stroke="#e8e2d8" strokeDasharray="4 6"/><path d={trendPeriod === '30天' ? 'M0 99 C35 95 46 104 75 90 S123 90 148 78 S197 91 220 65 S272 73 294 57 S352 64 377 42 S417 50 440 33' : trendPeriod === '90天' ? 'M0 117 C40 100 76 112 116 94 S178 91 215 78 S274 75 310 59 S380 65 440 33' : 'M0 124 C54 120 80 100 117 108 S190 80 224 91 S301 65 342 52 S400 48 440 33'} fill="none" stroke="#8b6d3c" strokeWidth="3" strokeLinecap="round"/><circle cx="440" cy="33" r="5" fill="#8b6d3c"/></svg><div className="g113-trend-axis"><span>{trendPeriod}前</span><span>今天</span></div></div></div><div className="g113-disclaimer">游戏内行情，仅供娱乐，不构成任何购买或投资建议。所有数值为 Demo 演示。</div><section><SectionHead title="今日在售" note="每件先看档案，再决定是否收入仓库。"/><div className="g113-chip-row">{[{ id: 'all', name: '全部' }, ...HOBBIES.map((h) => ({ id: h.id, name: h.name }))].map((x) => <button key={x.id} className={marketFilter === x.id ? 'active' : ''} onClick={() => setMarketFilter(x.id)}>{x.name}</button>)}</div><div className="g113-item-grid">{items.map((x) => <ItemCard key={x.id} item={x}/>)}</div></section></div>; }
    if (page === 'item') { const item = itemById(subId); if (!item) return <div className="g113-page"><Subhead title="未找到藏品" back="market"/></div>; const owned = state.owned.includes(item.id); return <div className="g113-page"><Subhead title="藏品档案" kicker={`${hobbyById(item.hobbyId)?.name} / ${item.tier}`} back={owned ? 'warehouse' : 'market'}/><div className="g113-detail-grid"><Image source={item.image} alt={`${item.name}示意图`} className="g113-detail-photo"/><div className="g113-detail-panel"><Eyebrow>COLLECTIBLE RECORD / 演示藏品</Eyebrow><h2>{item.name}</h2><p className="g113-detail-sub">{item.subtitle}</p><p>{item.description}</p><div className="g113-detail-price"><span>游戏内参考雅钱</span><strong>◎ {ya(item.price)}</strong><small>今日演示变动 {item.change > 0 ? '+' : ''}{item.change.toFixed(1)}%</small></div><div className="g113-detail-actions"><Action onClick={() => owned ? go(`inspect/${item.id}`) : buy(item)} icon="arrow">{owned ? '细看这件' : '放入待鉴区'}</Action><Action ghost onClick={() => update((s) => toggleBookmark(s, item.id))} icon="heart">{state.bookmarks.includes(item.id) ? '已收藏档案' : '收藏档案'}</Action>{owned && <><Action ghost onClick={() => go(`care/${item.id}`)}>养护入口</Action><Action ghost onClick={() => sell(item)}>演示卖出</Action></>}</div><p className="g113-demo-note">演示图片不用于真伪、品相或价格判断；演示买入只在本机记账。</p></div></div><div className="g113-paper g113-detail-info"><SectionHead title="这件藏品的档案" note="正式版将由真实照片与审校资料构成。"/><div>{item.details.map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div></div><div className="g113-disclaimer">游戏内行情，仅供娱乐，不构成任何购买或投资建议。</div></div>; }
    if (page === 'warehouse') return <div className="g113-page"><div className="g113-page-intro"><Eyebrow>MY COLLECTION / 仓库</Eyebrow><h1>把喜欢的，慢慢收进生活。</h1><p>收藏不在于多，而在于你渐渐看懂了它们。</p></div><div className="g113-warehouse-stats"><div><span>我的藏品</span><strong>{ownedItems.length}</strong><small>件虚拟藏品</small></div><div><span>待鉴区</span><strong>{pending.length}</strong><small>件等你细看</small></div><div><span>已关注</span><strong>{state.following.length}</strong><small>门兴趣</small></div></div>{pending.length > 0 && <section><SectionHead title="待鉴区" note="先认识它，再正式放进自己的收藏故事。"/><div className="g113-pending-list">{pending.map((id) => { const item = itemById(id)!; return <div key={id} className="g113-pending"><img src={item.image.src} alt={`${item.name}示意图`}/><div><small>{hobbyById(item.hobbyId)?.name} · AI 示意图</small><h3>{item.name}</h3><p>等待细看与知识卡学习</p></div><Action onClick={() => go(`inspect/${id}`)} icon="arrow">去细看</Action></div>; })}</div></section>}<section><SectionHead title="我的收藏" note="演示仓库只保存在这台设备的浏览器中。" action="逛逛市集" onAction={() => go('market')}/>{ownedItems.length ? <div className="g113-item-grid">{ownedItems.map((item) => <ItemCard key={item.id} item={item}/>)}</div> : <div className="g113-empty"><h2>仓库还空着</h2><p>先到市集认识一件藏品，慢慢开始。</p><Action onClick={() => go('market')}>去市集看看</Action></div>}</section><div className="g113-warehouse-feature"><div><Eyebrow>CARE / 养护玩法接入位</Eyebrow><h2>擦擦亮，留给下一阶段。</h2><p>这里将接入 Apollo 的步数制三消。当前可以预览棋盘界面，但不会产出保养品或改变品相。</p><Action ghost onClick={() => go('play')} icon="arrow">预览玩法界面</Action></div><Icon name="spark" size={62}/></div></div>;
    if (page === 'inspect') { const item = itemById(subId); if (!item) return <div className="g113-page"><Subhead title="未找到藏品" back="warehouse"/></div>; return <div className="g113-page"><Subhead title="细看 · 找门道" kicker={item.name} back="warehouse"/><div className="g113-inspect"><div className="g113-inspect-image"><Image source={item.image} alt={`${item.name}细看示意图`}/>{item.spots.map((spot, i) => <button key={spot.title} style={{ left: `${spot.x}%`, top: `${spot.y}%` }} className="g113-hotspot" onClick={() => setSelectedSpot(i)} aria-label={`查看知识点：${spot.title}`}>{i + 1}</button>)}</div><div className="g113-inspect-side"><Eyebrow>KNOW THE DETAILS</Eyebrow><h2>每一处细节，<br/>都是一个新发现。</h2><p>点选照片上的数字，阅读知识卡。真正的找点判定、缩放与奖励会在游戏阶段接入 Apollo。</p><div className="g113-demo-note">当前为页面流程示意；AI 图片不可用于真实鉴定。</div>{selectedSpot !== null && <div className="g113-knowledge"><small>知识卡 0{selectedSpot + 1}</small><h3>{item.spots[selectedSpot].title}</h3><p>{item.spots[selectedSpot].body}</p><button onClick={() => setSelectedSpot(null)}>收起知识卡</button></div>}<Action ghost onClick={() => { update((s) => ({ ...s, inspected: s.inspected.includes(item.id) ? s.inspected : [...s.inspected, item.id] })); notify('已完成页面演示 · 未发放游戏奖励'); go('warehouse'); }}>完成演示，返回仓库</Action></div></div></div>; }
    if (page === 'play') return <div className="g113-page"><Subhead title="擦擦亮" kicker="APOLLO GAME SLOT / 玩法界面预览" back="warehouse"/><div className="g113-play-preview"><div className="g113-play-copy"><Eyebrow>慢慢玩 · 不计时</Eyebrow><h2>一局轻松的保养时光。</h2><p>正式版会使用 Apollo 三消棋盘与拖拽交换能力。此刻只预览布局，不响应交换、不产出材料。</p><div className="g113-demo-note">游戏阶段暂缓接入 · 棋盘为静态示意</div></div><div className="g113-play-board"><div className="g113-play-board-head"><span>剩余步数 <b>18</b></span><span>目标 · 保养品</span></div><div className="g113-tiles">{Array.from({ length: 49 }, (_, i) => <span key={i} className={`t${(i * 7 + Math.floor(i / 7) * 3 + i % 4) % 5}`}>{['✦', '◈', '●', '◆', '✿'][(i * 7 + Math.floor(i / 7) * 3 + i % 4) % 5]}</span>)}</div></div></div></div>;
    if (page === 'care') { const item = itemById(subId); return <div className="g113-page"><Subhead title="藏品养护" kicker={item?.name || ''} back="warehouse"/><div className="g113-two-col"><div className="g113-paper"><h2>一件好物，值得用心照料。</h2><p>养护流程与品相变化会在 Apollo 游戏阶段接入。当前展示入口及信息结构。</p><Action onClick={() => go('play')} icon="arrow">预览擦擦亮</Action></div>{item && <Image source={item.image} alt={`${item.name}示意图`}/>}</div></div>; }
    if (page === 'community') { const own = state.ownPosts.map((p) => ({ ...p, author: '我', initials: '我', time: '刚刚', image: hobbyById(p.hobbyId)!.image, likes: 0, comments: 0 })); const posts = [...own, ...DEMO_POSTS]; return <div className="g113-page"><div className="g113-page-intro g113-community-intro"><div><Eyebrow>THE COMMUNITY / 同好</Eyebrow><h1>有趣的事，值得一起聊。</h1><p>把收藏、手艺与新学到的门道，分享给懂它的人。</p></div><Action onClick={() => go('compose')} icon="plus">分享见闻</Action></div><div className="g113-demo-note g113-community-banner">这里是本机演示社区：示例帖子、点赞与发帖仅用于体验流程；没有真实用户、云端上传或公开发布。</div><div className="g113-community-layout"><div><SectionHead title="同好正在聊" note="先听听大家最近发现了什么。"/><div className="g113-feed">{posts.map((p) => <article key={p.id} className="g113-post"><div className="g113-post-author"><span className="g113-avatar">{p.initials}</span><div><b>{p.author}</b><small>{hobbyById(p.hobbyId)?.name}圈 · {p.time}</small></div></div><button className="g113-post-body" onClick={() => go(`post/${p.id}`)}><h3>{p.title}</h3><p>{p.text}</p>{p.author !== '我' && <Image source={p.image} alt={`${p.title}示意图`}/>}</button><div className="g113-post-actions"><button onClick={() => update((s) => toggleLike(s, p.id))}><Icon name="heart" size={18}/>{p.likes + (state.likedPosts.includes(p.id) ? 1 : 0)} 赞同</button><button onClick={() => go(`post/${p.id}`)}>◎ {p.comments} 评论</button><button onClick={() => go(`circle/${p.hobbyId}`)}>进入兴趣圈 →</button></div></article>)}</div></div><aside className="g113-community-aside"><Eyebrow>FIND YOUR PEOPLE</Eyebrow><h2>逛逛兴趣圈</h2>{HOBBIES.slice(0, 4).map((h) => <button key={h.id} onClick={() => go(`circle/${h.id}`)}><img src={h.image.src} alt="圈子示意图"/><span><b>{h.name}圈</b><small>{h.people}</small></span><Icon name="arrow" size={16}/></button>)}<p>真实互动与内容审核将在后端接入后开放。</p></aside></div></div>; }
    if (page === 'circle') { const h = hobbyById(subId); return <div className="g113-page"><Subhead title={`${h?.name || '兴趣'}圈`} kicker="同好交流 · 本机演示" back="community"/><div className="g113-hobby-hero"><Image source={h?.image || HOBBIES[0].image} alt="兴趣圈示意图"/><div><Eyebrow>{h?.people}</Eyebrow><h2>在这里，聊聊{h?.name}。</h2><p>分享真实的经验，向同好请教，也看看别人的收藏故事。</p><Action onClick={() => go('compose')} icon="plus">写一条分享</Action></div></div><SectionHead title="圈内话题"/><div className="g113-feed">{DEMO_POSTS.filter((p) => p.hobbyId === subId).map((p) => <button className="g113-learn-row" key={p.id} onClick={() => go(`post/${p.id}`)}><span className="g113-avatar">{p.initials}</span><b>{p.title}</b><Icon name="arrow"/></button>)}</div></div>; }
    if (page === 'post') { const p = DEMO_POSTS.find((x) => x.id === subId) || state.ownPosts.find((x) => x.id === subId); if (!p) return <div className="g113-page"><Subhead title="未找到分享" back="community"/></div>; const own = DEMO_POSTS.find((x) => x.id === subId) || { ...p, author: '我', initials: '我', time: '刚刚', image: hobbyById(p.hobbyId)!.image, likes: 0, comments: 0 }; return <div className="g113-page"><Subhead title="同好分享" kicker={`${hobbyById(own.hobbyId)?.name}圈`} back="community"/><div className="g113-post-detail g113-paper"><div className="g113-post-author"><span className="g113-avatar">{own.initials}</span><div><b>{own.author}</b><small>{own.time} · 本机演示</small></div></div><h2>{own.title}</h2><p>{own.text}</p>{own.author !== '我' && <Image source={own.image} alt="帖子示意图"/>}<div className="g113-post-actions"><button onClick={() => update((s) => toggleLike(s, own.id))}><Icon name="heart" size={18}/>{own.likes + (state.likedPosts.includes(own.id) ? 1 : 0)} 赞同</button><button onClick={() => go(`circle/${own.hobbyId}`)}>进入{hobbyById(own.hobbyId)?.name}圈 →</button></div><div className="g113-comment-preview"><h3>评论与掌眼</h3><p>真实评论、掌眼和举报依赖账户、内容审核与云端服务；目前只展示页面入口。</p><textarea placeholder="真实社区开放后，在这里交流你的看法" disabled/><button disabled>暂未开放发布</button></div></div></div>; }
    if (page === 'compose') return <div className="g113-page"><Subhead title="分享一件有趣的事" kicker="CREATE / 本机演示" back="community"/><div className="g113-compose g113-paper"><div className="g113-demo-note">本机演示：文字仅保存在当前浏览器；照片不会上传、保存或公开发布。正式版必须先有真实用户账户与内容审核。</div><label>选择兴趣圈<select value={draft.hobbyId} onChange={(e) => setDraft({ ...draft, hobbyId: e.target.value as HobbyId })}>{HOBBIES.map((h) => <option key={h.id} value={h.id}>{h.name}</option>)}</select></label><label>标题<input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} maxLength={50} placeholder="今天想分享什么？"/></label><label>说说你的故事<textarea value={draft.text} onChange={(e) => setDraft({ ...draft, text: e.target.value })} maxLength={500} rows={7} placeholder="一段经历、一个问题，或你新学到的门道……"/></label><label className="g113-upload"><Icon name="camera"/> 选择真藏照片（只预览文件名）<input type="file" accept="image/*" onChange={(e) => setUploadName(e.target.files?.[0]?.name || '')}/></label>{uploadName && <p className="g113-upload-name">已选：{uploadName} · 此 Demo 不上传或保存图片</p>}<Action disabled={!draft.title.trim() || !draft.text.trim()} onClick={() => { const post = { id: `local-${Date.now()}`, title: draft.title.trim(), text: draft.text.trim(), hobbyId: draft.hobbyId }; update((s) => ({ ...s, ownPosts: [post, ...s.ownPosts] })); setDraft({ title: '', text: '', hobbyId: 'watch' }); setUploadName(''); notify('已加入本机演示社区，未公开发布'); go('community'); }} icon="arrow">保存本机演示分享</Action></div></div>;
    if (page === 'profile') return <div className="g113-page"><Subhead title="我的雅趣" kicker="PROFILE / 第二人生" back="home"/><div className="g113-profile-hero"><span className="g113-profile-avatar">雅</span><div><Eyebrow>兴趣探索者</Eyebrow><h2>从喜欢的一件事开始</h2><p>你已关注 {state.following.length} 门爱好，仓库里有 {ownedItems.length} 件演示藏品。</p></div></div><div className="g113-profile-links"><button onClick={() => go('wallet')}><Icon name="coin"/><span><b>雅钱与明细</b><small>查看来源与本机演示记录</small></span><Icon name="arrow"/></button><button onClick={() => go('exam')}><Icon name="book"/><span><b>学习与证书</b><small>无时限小考 · 知识成长</small></span><Icon name="arrow"/></button><button onClick={() => go('settings')}><Icon name="settings"/><span><b>设置与显示</b><small>大字模式 · 图片说明 · 隐私</small></span><Icon name="arrow"/></button></div><div className="g113-paper"><Eyebrow>MY INTERESTS</Eyebrow><h2>我的兴趣</h2><div className="g113-chip-row">{state.interests.length ? state.interests.map((id) => <button key={id} onClick={() => openHobby(id)}>{hobbyById(id)?.name}</button>) : <p>还没选择兴趣。去发现页，先从好奇开始。</p>}</div></div></div>;
    if (page === 'wallet') return <div className="g113-page"><Subhead title="雅钱与明细" kicker="WALLET / 只在游戏内流转" back="profile"/><div className="g113-wallet-hero"><span>演示雅钱余额</span><strong>◎ {ya(state.balance)}</strong><p>雅钱不能提现、不能赠送、不能兑换真实物品。此处为本机演示账户。</p></div><div className="g113-three-col"><div className="g113-paper"><Icon name="book"/><h3>学习与考级</h3><p>阅读知识卡、完成小考，获得成长与奖励。</p><Action ghost onClick={() => go('exam')}>查看小考</Action></div><div className="g113-paper"><Icon name="people"/><h3>优质分享</h3><p>未来经审核通过的真藏分享，可以获得社区贡献奖励。</p><Action ghost onClick={() => go('compose')}>去分享</Action></div><div className="g113-paper"><Icon name="spark"/><h3>主动观看广告</h3><p>正式版由你主动选择；本 Demo 不播放广告，也不发奖励。</p><Action ghost onClick={() => notify('演示版未接入广告，不发放雅钱')}>了解规则</Action></div></div><section><SectionHead title="本机演示明细"/><div className="g113-ledger">{state.ledger.map((x) => <div key={x.id}><span>{x.label}</span><b className={x.amount < 0 ? 'down' : ''}>{x.amount > 0 ? '+' : ''}{ya(x.amount)}</b></div>)}</div></section></div>;
    if (page === 'exam') return <div className="g113-page"><Subhead title="学识小考" kicker="LEARN / 无时限" back="profile"/><div className="g113-exam g113-paper"><Eyebrow>机械表 · 入门小考 / 页面预览</Eyebrow><h2>一枚机械表里，负责调节走时节奏的部件是什么？</h2><p>不着急，选一个你觉得对的答案。</p>{['摆轮与擒纵机构', '表带', '表扣'].map((x, i) => <button key={x} className={`g113-answer ${examAnswer === i ? 'selected' : ''}`} onClick={() => setExamAnswer(i)}><span>{String.fromCharCode(65 + i)}</span>{x}</button>)}{examAnswer !== null && <div className="g113-exam-result"><b>{examAnswer === 0 ? '答对了。' : '再认识一下这个知识点。'}</b><p>摆轮与擒纵机构共同控制能量释放的节奏。正式考级的题库、成绩和雅钱奖励仍待 Apollo 玩法接入。</p></div>}<div className="g113-demo-note">这里只预览考试页面，不计分、不发证书或雅钱。</div></div></div>;
    if (page === 'settings') return <div className="g113-page"><Subhead title="设置" kicker="PREFERENCES" back="profile"/><div className="g113-settings g113-paper"><h2>显示与阅读</h2><label className="g113-setting-row"><span><b>大字模式</b><small>放大正文与操作文字，方便舒适阅读。</small></span><input type="checkbox" checked={state.largeText} onChange={(e) => update((s) => ({ ...s, largeText: e.target.checked }))}/></label><div className="g113-setting-row"><span><b>图片真实性说明</b><small>目前所有藏品照片是 AI 示意图，不作鉴定依据。正式版将接入可核验实物照片。</small></span></div><div className="g113-setting-row"><span><b>演示数据</b><small>收藏、雅钱和帖子只保存在本机浏览器，不与他人共享。</small></span></div><button className="g113-clear-demo" onClick={() => setDialog({ title: '清除本机演示数据？', body: '这会清除你在当前浏览器里的兴趣选择、演示收藏、雅钱明细和文字分享，不能撤销。', action: '清除数据', run: () => { setState(INITIAL_STATE); setDialog(null); go('welcome'); } })}>清除本机演示数据</button>{onExit && <button className="g113-inline-link" onClick={onExit}>返回 Apollo 游戏库</button>}</div></div>;
    return <div className="g113-page"><Subhead title="这页还没有找到" back="home"/><Action onClick={() => go('home')}>回到首页</Action></div>;
  })();

  return <div className={`g113-app ${state.largeText ? 'g113-app--large' : ''}`}><header className="g113-header"><button className="g113-brand" onClick={() => go('home')}><span>雅趣<span className="g113-brand-dot">·</span>第二人生</span><small>兴 趣 ， 让 生 活 继 续 发 光</small></button><nav className="g113-desktop-nav" aria-label="主导航">{NAV.map((n) => <button key={n.id} className={active === n.id ? 'active' : ''} onClick={() => go(n.id)}>{n.label}</button>)}</nav><div className="g113-header-actions"><button className="g113-wallet-short" onClick={() => go('wallet')} title="雅钱与明细"><Icon name="coin" size={21}/><span>雅钱 <b>{ya(state.balance)}</b></span></button><button className="g113-header-avatar" onClick={() => go('profile')} aria-label="我的雅趣"><Icon name="user" size={22}/></button></div></header><div className="g113-demo-ribbon"><span>APP DEMO</span> 当前为应用流程原型 · AI 图片仅作示意 · 游戏与真实社交尚未接入</div><main>{main}</main><footer className="g113-footer"><div><b>雅趣 · 第二人生</b><p>让兴趣，陪你继续走一段。</p></div><span>演示版 · 虚拟藏品与本机数据 · 不构成投资建议</span></footer><nav className="g113-mobile-nav" aria-label="手机主导航">{NAV.map((n) => <button key={n.id} className={active === n.id ? 'active' : ''} onClick={() => go(n.id)}><Icon name={n.icon} size={22}/><span>{n.label}</span></button>)}</nav>{notice && <div className="g113-toast" role="status">{notice}</div>}{dialog && <div className="g113-modal-layer" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && setDialog(null)}><div className="g113-modal" role="dialog" aria-modal="true" aria-label={dialog.title}><button className="g113-modal-close" onClick={() => setDialog(null)} aria-label="关闭"><Icon name="close"/></button><Eyebrow>APPLICATION DEMO</Eyebrow><h2>{dialog.title}</h2><p>{dialog.body}</p><div><Action ghost onClick={() => setDialog(null)}>再想想</Action><Action onClick={dialog.run}>{dialog.action}</Action></div></div></div>}</div>;
}
