/** 清酒馆的酒藏导览资料。仅用于成人文化学习，不是酒款评分、售价或购买推荐。 */
export type SakeBrand = {
  id: string;
  name: string;
  romanized: string;
  prefecture: string;
  area: string;
  brewery: string;
  focus: string;
  story: string;
  example: string;
  exampleClass?: string;
  exampleFlavor?: string;
  flavorSourceUrl?: string;
  lookFor: string;
  source: { label: string; url: string };
  photo?: { src: string; alt: string; credit: string; sourceUrl: string; license: 'CC0' };
};

const BRAND_ENTRIES: readonly SakeBrand[] = [
  { id: 'dassai', name: '獺祭', romanized: 'DASSAI', prefecture: '山口', area: '岩国', brewery: '獺祭', focus: '数字与精米步合', story: '从山口岩国出发，官方产品目录把 23、39、45 等数字明确写进代表系列名称，很适合练习把标签数字读成资料，而不是高低分。', example: '獺祭 45 / 39 / 23', exampleClass: '纯米大吟酿系列', exampleFlavor: '以 45 为例：官方描述为米的细腻甘味与华丽香气。', flavorSourceUrl: 'https://dassai.com/cn/product/main/45.html', lookFor: '同一系列的名称、精米步合与版本差异。', source: { label: '獺祭官方产品目录', url: 'https://dassai.com/us/product/' } },
  { id: 'hakkaisan', name: '八海山', romanized: 'HAKKAISAN', prefecture: '新潟', area: '南鱼沼', brewery: '八海酿造', focus: '雪国与地域', story: '酒藏位于新潟县南鱼沼。读它的资料，可以把水、米与雪国地域故事分开记录，再回到具体标签核对。', example: '八海山 特别本酿造', exampleClass: '特别本酿造', exampleFlavor: '酒藏把这款描述为柔和、清爽的风格。', flavorSourceUrl: 'https://www.hakkaisan.com/our-products/hakkaisan-tokubetsu-honjozo/', lookFor: '酒米、精米步合和酒藏所在地分别来自哪一栏。', source: { label: '八海山官方酒藏介绍', url: 'https://www.hakkaisan.com/our-brewery/' } },
  { id: 'kubota', name: '久保田', romanized: 'KUBOTA', prefecture: '新潟', area: '长冈', brewery: '朝日酒造', focus: '系列与酒标结构', story: '久保田是新潟朝日酒造的品牌；“千寿”“万寿”等系列名与“吟酿”“纯米大吟酿”等分类词应分开读。', example: '久保田 千寿', exampleClass: '吟酿', exampleFlavor: '酒藏描述为香气克制、旨味与微酸相伴、收尾清爽。', flavorSourceUrl: 'https://www.asahi-shuzo.co.jp/global/en/products/kubota/senjyu/', lookFor: '先辨认品牌、系列、分类，再记录酒米和精米步合。', source: { label: '朝日酒造官方品牌页', url: 'https://www.asahi-shuzo.co.jp/global/en/' } },
  { id: 'dewazakura', name: '出羽樱', romanized: 'DEWAZAKURA', prefecture: '山形', area: '天童', brewery: '出羽樱酒造', focus: '吟酿的普及故事', story: '山形天童的出羽樱在官方资料中记载了“樱花吟酿”于 1980 年推出的背景，适合从一个系列认识吟酿文化的传播。', example: '出羽樱 樱花吟酿', exampleClass: '吟酿', exampleFlavor: '酒藏以果香与爽快感来介绍樱花吟酿。', flavorSourceUrl: 'https://www.dewazakura.co.jp/item/cat03/oka.html', lookFor: '产品推出时期、分类和酒标版本如何记录。', source: { label: '出羽樱官方酒款资料', url: 'https://www.dewazakura.co.jp/en/item/cat03/oka.html' } },
  { id: 'tatenokawa', name: '楯野川', romanized: 'TATENOKAWA', prefecture: '山形', area: '酒田', brewery: '楯野川', focus: '一座酒藏的系列地图', story: '山形酒田的楯野川在官方目录中按多个系列整理产品，并明确以纯米大吟酿为核心；适合比较“系列”和“特定名称”这两个层级。', example: '楯野川 清流（Basic）', exampleClass: '纯米大吟酿', exampleFlavor: '官方描述清流为轻盈、带果香与柔和酸感。', flavorSourceUrl: 'https://tatenokawa.com/en/sake/products/products.html?category=5', lookFor: '同一酒藏的系列、酒米与设计语言。', source: { label: '楯野川官方系列目录', url: 'https://tatenokawa.com/en/sake/products/' } },
  { id: 'gekkeikan', name: '月桂冠', romanized: 'GEKKEIKAN', prefecture: '京都', area: '伏见', brewery: '月桂冠', focus: '伏见与品牌演变', story: '月桂冠的酒藏文化与京都伏见相连。官方目录将“凤麟”等系列与月桂冠主线并列展示，可从包装与命名看品牌层级。', example: '凤麟 纯米大吟酿', exampleClass: '纯米大吟酿', exampleFlavor: '品牌把凤麟描述为清爽、甜润，并带有果香线索。', flavorSourceUrl: 'https://www.gekkeikan.com/horin/', lookFor: '产地、系列名、分类词在标签上的位置。', source: { label: '月桂冠官方产品目录', url: 'https://www.gekkeikan.com/products/' } },
  { id: 'kikumasamune', name: '菊正宗', romanized: 'KIKU-MASAMUNE', prefecture: '兵库', area: '神户·滩', brewery: '菊正宗酒造', focus: '生酛与传统工艺', story: '菊正宗的官方资料介绍了滩地区背景和生酛造法。把酿造方法与酒款分类放在同一张观察卡，能避免只凭品牌名判断。', example: '上撰 生酛 本酿造', exampleClass: '本酿造', exampleFlavor: '酒藏描述这款为偏辛、利落而有力度的风格。', flavorSourceUrl: 'https://www.kikumasamune.co.jp/products/brand/honjou/', lookFor: '“生酛”是工艺词，“本酿造”是分类词。', source: { label: '菊正宗官方生酛资料', url: 'https://www.kikumasamune.co.jp/products/brand/honjou/' } },
  { id: 'hakutsuru', name: '白鹤', romanized: 'HAKUTSURU', prefecture: '兵库', area: '神户·滩', brewery: '白鹤酒造', focus: '酒米与酒藏历史', story: '白鹤的酒藏位于神户滩地区；官方历史资料也介绍了自有酒米“白鹤锦”的培育，可由一粒米延伸到酿造档案。', example: '白鹤锦 纯米大吟酿', exampleClass: '纯米大吟酿', exampleFlavor: '官方对这款的描述包含花香、果香与柔和的层次。', flavorSourceUrl: 'https://www.hakutsuru-sake.com/product/hakutsuru-nishiki-junmai-daiginjo/', lookFor: '酒米名称、产区资料和酒藏历史分别依据什么来源。', source: { label: '白鹤官方酒藏历史', url: 'https://www.hakutsuru-sake.com/our-story/' }, photo: { src: '/games/game113/real/hakutsuru-brewery-cc0.jpg', alt: '日本神户的白鹤酒造建筑真实照片', credit: '摄影 岩佐栄三 · 2017', sourceUrl: 'https://commons.wikimedia.org/wiki/File:HAKUTSURU_SAKE_BREWING.jpg', license: 'CC0' } },
  { id: 'aramasa', name: '新政', romanized: 'ARAMASA', prefecture: '秋田', area: '秋田市', brewery: '新政酒造', focus: '六号酵母、年份与保存', story: '新政的 No.6 与 Colors 是不同的作品线。先认酒款、酿造年度与是否火入，才能读懂它的收藏档案。', example: 'No.6 / Colors', exampleClass: '不同作品线，逐款核对', lookFor: '先区分生酒与火入、酿造年度和出荷月份。', source: { label: '新政官方作品目录', url: 'https://www.aramasa.jp/collection/' } },
  { id: 'kuheiji', name: '醸し人九平次', romanized: 'KUHEIJI', prefecture: '爱知', area: '名古屋', brewery: '萬乗醸造', focus: '田块、米种与年份', story: '九平次的官方作品目录将酒米与年份写进作品脉络；从田地出发，比先看价格更能读出其个性。', example: 'EAU DU DÉSIR / SAUVAGE', exampleClass: '同系列的不同米种', lookFor: '并排记录山田锦与雄町，不将风味差异直接解释成高低。', source: { label: '九平次官方作品目录', url: 'https://kuheiji.co.jp/kamoshibito/desir-et-sauvage/' } },
  { id: 'kazenomori', name: '风之森', romanized: 'KAZE NO MORI', prefecture: '奈良', area: '御所', brewery: '油长酒造', focus: '米种、精米与菩提酛', story: '风之森以秋津穂、露叶风等不同米种与精米设置建立系列；数字是阅读工艺的入口，不是评分。', example: '秋津穂 657 / 露叶风 507', exampleClass: '米种 × 精米步合', lookFor: '把系列代码拆成米种与精米步合两栏。', source: { label: '油长酒造官方产品页', url: 'https://yucho-sake.jp/product/kazenomori/' } },
  { id: 'juyondai', name: '十四代', romanized: 'JUYONDAI', prefecture: '山形', area: '村山', brewery: '高木酒造', focus: '品牌与酒藏谱系', story: '村山市公开的酒藏资料列出高木酒造的十四代与朝日鹰。这里先建立品牌—酒藏—地域的基础档，不用流通价格定义它。', example: '十四代', lookFor: '具体酒款、米种、年份和标签版本需要逐瓶核验。', source: { label: '山形县村山市 · 高木酒造资料', url: 'https://www.city.murayama.lg.jp/kigyo/gyoshu/sake/takagi.html' } },
  { id: 'jikon', name: '而今', romanized: 'JIKON', prefecture: '三重', area: '名张', brewery: '木屋正酒造', focus: '同一品牌的不同酒米', story: '木屋正酒造官方列出山田锦、雄町等不同米种的而今作品，适合从酒米建立一份作品索引。', example: '而今 纯米吟酿 山田锦 / 雄町', exampleClass: '纯米吟酿', lookFor: '不要只记“而今”：再写酒米、年份与具体版本。', source: { label: '木屋正酒造官方 · 而今', url: 'https://kiyashow.com/jikon.html' } },
  { id: 'denshu', name: '田酒', romanized: 'DENSHU', prefecture: '青森', area: '青森市', brewery: '西田酒造店', focus: '从田与米认识纯米酒', story: '青森县酒造组合记载西田酒造店的田酒及其纯米酒脉络，品牌名称本身就值得追问米与田的关系。', example: '田酒 特别纯米', exampleClass: '特别纯米', lookFor: '先记录“纯米”的原料条件，再看不同米种与款式。', source: { label: '青森县酒造组合 · 西田酒造店', url: 'https://aomori-sake.or.jp/kuramoto/denshu.html' } },
  { id: 'nabeshima', name: '锅岛', romanized: 'NABESHIMA', prefecture: '佐贺', area: '鹿岛', brewery: '富久千代酒造', focus: '佐贺鹿岛的地方酒', story: '富久千代酒造官方以佐贺鹿岛的锅岛为核心品牌。先从地域与酒藏入手，代表款式再逐一核对。', example: '锅岛', lookFor: '区分品牌名与单款名称，记录所见版本。', source: { label: '富久千代酒造官方', url: 'https://nabeshima.biz/' } },
  { id: 'kokuryu', name: '黑龙', romanized: 'KOKURYU', prefecture: '福井', area: '永平寺', brewery: '黑龙酒造', focus: '越前酒藏与作品线', story: '黑龙酒造位于福井永平寺町，品牌资料可从酒藏历史、当地水系与系列命名展开。', example: '黑龙', lookFor: '同一酒藏的不同作品线需要分别建档。', source: { label: '黑龙酒造官方', url: 'https://www.kokuryu.co.jp/' } },
  { id: 'born', name: '梵', romanized: 'BORN', prefecture: '福井', area: '鲭江', brewery: '加藤吉平商店', focus: '越前的酒藏文化', story: '加藤吉平商店官方将“梵”作为核心品牌。先认识酒藏与地域，再进入具体作品的工艺与版本。', example: '梵', lookFor: '查酒款全名、年份和实际标签，避免用品牌名代替作品名。', source: { label: '加藤吉平商店官方', url: 'https://www.born.co.jp/' } },
  { id: 'senkin', name: '仙禽', romanized: 'SENKIN', prefecture: '栃木', area: '樱花市', brewery: 'せんきん', focus: '地方米与酒藏设计', story: '仙禽官方资料以栃木樱花市为据点，作品目录并列 Nature、Modern、Retro 等表达，适合观察品牌内部的不同方向。', example: 'Modern Senkin / Retro Senkin', lookFor: '把系列名称、酒米与年份分别记录。', source: { label: '仙禽官方作品目录', url: 'https://senkin.co.jp/' } },
  { id: 'zaku', name: '作', romanized: 'ZAKU', prefecture: '三重', area: '铃鹿', brewery: '清水清三郎商店', focus: '作品命名与酿造观', story: '清水清三郎商店在铃鹿酿造“作”，官方资料从品牌命名与酿造过程解释这条作品线。', example: '作', lookFor: '从品牌进入具体系列与标签，不凭单字名称推测酒款。', source: { label: '清水清三郎商店官方 · 作', url: 'https://seizaburo.jp/zaku/' } },
  { id: 'hakurakusei', name: '伯乐星', romanized: 'HAKURAKUSEI', prefecture: '宫城', area: '川崎', brewery: '新泽酿造店', focus: '食中酒的设计', story: '新泽酿造店以“究极的食中酒”介绍伯乐星；酒藏资料同时列出三本木本社与川崎蔵，建档时不应混为同一地址。', example: '伯乐星', lookFor: '分清品牌、制造蔵与公司本社，之后再追具体酒款。', source: { label: '新泽酿造店官方', url: 'https://niizawa-brewery.mom/' } },
  { id: 'nanbubijin', name: '南部美人', romanized: 'NANBU BIJIN', prefecture: '岩手', area: '二户', brewery: '南部美人', focus: '从一座酒藏读酿造全过程', story: '南部美人官网按米、水、麹、酵母、醪与火入等环节介绍酿造，适合建立工艺词汇的第一张地图。', example: '南部美人', lookFor: '同一酒藏不同酒款，应分清米种、火入与保存方式。', source: { label: '南部美人官方 · 酒造', url: 'https://www.nanbubijin.co.jp/' } },
  { id: 'masumi', name: '真澄', romanized: 'MASUMI', prefecture: '长野', area: '诹访', brewery: '宫坂酿造', focus: '诹访与七号酵母', story: '宫坂酿造官方介绍真澄的诹访酒藏与七号酵母历史；从“酵母”切入可理解酒藏对风格的长期研究。', example: '真澄', lookFor: '先读酒藏历史，再分开记录具体酒款的酵母与年份。', source: { label: '宫坂酿造官方 · 真澄', url: 'https://www.masumi.co.jp/' } },
  { id: 'tengumai', name: '天狗舞', romanized: 'TENGUMAI', prefecture: '石川', area: '白山', brewery: '车多酒造', focus: '山廃仕込入门', story: '车多酒造在石川白山持续酿造天狗舞，其官方资料把山廃仕込作为重要的工艺线索。', example: '天狗舞 山廃仕込 纯米酒', exampleClass: '纯米酒 · 山廃仕込', lookFor: '“山廃”是酒母工艺，不是酒的品质等级。', source: { label: '车多酒造官方 · 天狗舞', url: 'https://www.tengumai.co.jp/' } },
  { id: 'suigei', name: '醉鲸', romanized: 'SUIGEI', prefecture: '高知', area: '高知市', brewery: '醉鲸酒造', focus: '土佐的地方酒', story: '醉鲸酒造的官方公司资料介绍高知长浜酒藏与常规作品线，适合把地域、酒藏与酒款分别记下。', example: '醉鲸 特别纯米 / 纯米吟酿 吟丽', lookFor: '同一品牌下的分类词与具体名称不要混写。', source: { label: '醉鲸酒造官方 · 公司档案', url: 'https://suigei.co.jp/company/about' } },
  { id: 'ugonotsuki', name: '雨后之月', romanized: 'UGO NO TSUKI', prefecture: '广岛', area: '吴', brewery: '相原酒造', focus: '酒名里的文学线索', story: '相原酒造官方写明“雨后之月”得名于德富芦花作品中的篇名；名字的来源可以是文化入口，而不是酒质证明。', example: '雨后之月', lookFor: '把命名故事与具体酒款的工艺资料分开存。', source: { label: '相原酒造官方', url: 'https://www.ugonotsuki.com/' } },
  { id: 'koshinokanbai', name: '越乃寒梅', romanized: 'KOSHI NO KANBAI', prefecture: '新潟', area: '新潟市', brewery: '石本酒造', focus: '新潟地方酒的变迁', story: '石本酒造官方以越乃寒梅讲述新潟的土地与酒藏历史；同一品牌会随时代推出不同作品，不宜把旧标签概括成所有现售酒。', example: '越乃寒梅', lookFor: '保留标签原貌与年代，旧款和当季款分别建档。', source: { label: '石本酒造官方 · 越乃寒梅', url: 'https://koshinokanbai.co.jp/' } },
  { id: 'kenbishi', name: '剑菱', romanized: 'KENBISHI', prefecture: '兵库', area: '神户·滩', brewery: '剑菱酒造', focus: '伊丹到滩的酒藏历史', story: '剑菱酒造官方记载从伊丹到滩的酿造历程；这是一条理解酒藏迁移与品牌延续的历史线索。', example: '剑菱', lookFor: '品牌延续不等于每一时期的酒液与工艺完全相同。', source: { label: '剑菱酒造官方 · 公司历史', url: 'https://www.kenbishi.co.jp/company/' } },
  { id: 'hitakami', name: '日高见', romanized: 'HITAKAMI', prefecture: '宫城', area: '石卷', brewery: '平孝酒造', focus: '港口城市与地方酒', story: '宫城县酒造组合将平孝酒造与石卷的地方文化联系起来，并单列日高见的具体产品资料，适合从产地走到单款。', example: '日高见 特别纯米酒', exampleClass: '特别纯米', lookFor: '核对每个产品页的批次和原料米，不把一期规格泛化。', source: { label: '宫城县酒造组合 · 平孝酒造', url: 'https://miyagisake.jp/kuramoto/hirakou/' } },
];

/** 默认目录按地域名称、再按品牌名称排列，不设编辑推荐位或品牌榜首。 */
export const SAKE_BRANDS: readonly SakeBrand[] = [...BRAND_ENTRIES].sort((a, b) =>
  a.prefecture.localeCompare(b.prefecture, 'zh-CN') || a.name.localeCompare(b.name, 'zh-CN'));
