/** A small set of bottle-level dossiers with independently checkable, source-specific claims. */
export const SAKE_EVIDENCE_FILES = [
  {
    id: 'jikon-tokuto-omachi',
    name: '而今 特等雄町',
    maker: '木屋正酒造 · 三重',
    result: 'SAKE COMPETITION 2026 · Super Premium 金奖第 1 位',
    resultUrl: 'https://www.sakecompetition.com/award.html',
    evidenceKind: '酒藏产品档案',
    reading: '木屋正酒造的产品目录列出「纯米大吟酿 特等雄町 火入」，容量 720ml / 1.8L，预计 11 月出货。赛事结果只写「而今 特等雄町」；目前不能据此确认参赛酒的火入状态、批次或容量。',
    evaluation: '赛事证明它在当届高端组获得第一；赛事未公开这瓶的逐项盲评意见，因此不添加具体香气或口感描述。',
    nuance: '同页「特上雄町」有独立酒米与参数说明，那些参数不能移植到「特等雄町」。',
    sourceUrl: 'https://kiyashow.com/sake/',
  },
  {
    id: 'tenbi-hotaten',
    name: '天美 纯米吟酿 蛍天',
    maker: '长州酒造 · 山口',
    result: 'SAKE COMPETITION 2026 · 纯米吟酿金奖第 10 位；IWC 2026 · Champion Sake',
    resultUrl: 'https://www.sakecompetition.com/award.html',
    extraResultUrl: 'https://www.internationalwinechallenge.com/trophy-results-2026.html',
    evidenceKind: '酒藏 2026 年作品说明',
    reading: '酒藏介绍这款限量初夏作品使用下关市丰田町的「西都之雫」与山口县产山田锦，原酒酒精度 13%。其描述有青苹果感的香气、柔和甜感、轻微气泡与酸度。',
    evaluation: '两个赛事分别给出上述结果；风味文字来自酒藏，而非两场比赛的逐瓶评委记录。赛事瓶与酒藏网页所述零售批次是否完全相同，现有公开资料尚未证明。',
    nuance: '这是罕见的跨赛事可对读线索，但不能把 IWC 总冠军换算为 SAKE COMPETITION 的跨组第一。',
    sourceUrl: 'https://choshusake.com/item/1902',
  },
  {
    id: 'juyondai-ryusen',
    name: '十四代 龍泉',
    maker: '高木酒造 · 山形',
    result: 'SAKE COMPETITION 2026 · Super Premium 铜奖（无逐瓶名次）',
    resultUrl: 'https://www.sakecompetition.com/award_silver.html',
    evidenceKind: '零售报价 · 非酒藏定价',
    reading: 'LIFE VACATION 银座店 2026-01-10 的含税列表展示 720ml「龍泉」¥269,500；同页「龍泉 白雲去来」是另一酒款，不能混用其价格。',
    evaluation: '赛事只确认铜奖，没有可核对的逐瓶品饮评语。零售页没有标出酿造年份，也不能把其在售瓶对应到赛事参赛批次。',
    nuance: '高价格与铜奖是两条不同口径的事实；不能据此推断性价比、二级市场成交价或未来涨跌。',
    sourceUrl: 'https://www.osake-kakaku.com/Juyondai.html',
  },
  {
    id: 'zaku-kaizan-ittekisui',
    name: '作 ZAKU Kaizan Ittekisui · 2025/2026',
    maker: '清水清三郎商店 · 三重',
    result: 'IWC 2026 · Mie Junmai Daiginjo Trophy',
    resultUrl: 'https://www.internationalwinechallenge.com/canopy/beverage_details?sid=21998',
    evidenceKind: 'IWC 公开逐瓶品饮笔记',
    reading: '评委笔记提到苹果、丁香、草莓与奶油面包层次；口感圆润，有细腻的乳脂质感。官网列酒精度 16.0%，组别为纯米大吟酿。',
    evaluation: '这是真正可追到单瓶的赛事评语，而不是本馆模拟试饮。该页未给出可供跨赛事比较的数值总分。',
    nuance: '年份写法以 IWC 酒款详情的「2025/2026」为准，不把它解释成具体出厂日期。',
    sourceUrl: 'https://www.internationalwinechallenge.com/canopy/beverage_details?sid=21998',
  },
  {
    id: 'born-premium-sparkling',
    name: '梵 Born: Premium Sparkling · 2024/2025',
    maker: '加藤吉平商店 · 福井',
    result: 'IWC 2026 · Sparkling Trophy',
    resultUrl: 'https://www.internationalwinechallenge.com/canopy/beverage_details?sid=23029',
    evidenceKind: 'IWC 公开逐瓶品饮笔记',
    reading: '评委笔记以枇杷、乳酸奶香与柠檬气息描绘香气；气泡细，口中有酸奶般的厚度，收尾清爽并带咸鲜感。官网列酒精度 14.5%，组别为起泡清酒。',
    evaluation: '这里有可核对的评语与奖项，但它属于 IWC 起泡组，不能与 SAKE COMPETITION 高端组做名次换算。',
    nuance: '瓶身及酒标实拍尚待授权；本馆先保留文字档案，不以 AI 图代替。',
    sourceUrl: 'https://www.internationalwinechallenge.com/canopy/beverage_details?sid=23029',
  },
] as const;
